/**
 * Agent-First Data (AFDATA) — suffix-driven output formatting and protocol templates.
 */

export {
  jsonResult,
  jsonError,
  jsonProgress,
  jsonLog,
  Event,
  EventBuildError,
  JsonResultBuilder,
  JsonErrorBuilder,
  JsonProgressBuilder,
  JsonLogBuilder,
  type LogLevel,
  validateProtocolEvent,
  validateProtocolStream,
  decodeProtocolEvent,
  type DecodedEvent,
  type DecodedResult,
  type DecodedError,
  type DecodedProgress,
  type DecodedLog,
  EventDecodeError,
  type JsonValue,
  RedactionPolicy,
  PlainStyle,
  type OutputOptions,
  outputOptionsForPolicy,
  redactedValue,
  redactUrlSecrets,
  normalizeUtcOffset,
  isValidRfc3339Date,
  isValidRfc3339Time,
  isValidRfc3339,
  isValidBcp47,
} from "./format.js";
export {
  type OutputFormat,
  type CliEventWriter,
  CliEmitter,
  LogFilters,
  cliParseOutput,
  cliParseLogFilters,
  render,
  buildCliError,
  buildCliVersion,
  cliRenderVersion,
  cliHandleVersionOrContinue,
} from "./cli.js";
