/**
 * Reusable Agent Skill installer for spore CLIs.
 *
 * A spore that embeds its `SKILL.md` describes itself with a {@link SkillSpec} and calls
 * {@link runSkillAdmin} to install, uninstall, or report status of that skill across
 * supported coding agents (Codex, Claude Code, opencode).
 *
 * The function performs the filesystem work and returns the protocol value (rendered by
 * the caller with `cliOutput`) or throws a {@link SkillError}. It never writes to
 * stdout/stderr itself.
 */

import * as fs from "node:fs";
import { join } from "node:path";

const SKILL_FILE_NAME = "SKILL.md";

/**
 * Identity of the skill being managed and the tool that manages it.
 *
 * `name` is both the skill directory name and the `name:` front-matter field. `source` is
 * the bundled `SKILL.md`. `title` is a human label for error messages. `markerSlug` seeds
 * the managed-skill marker and the `Generated by <slug> skill install` comment, and is
 * referenced in hints (e.g. `afwidget`).
 */
export interface SkillSpec {
  name: string;
  source: string;
  title: string;
  markerSlug: string;
}

/** The skill action to perform. */
export type SkillAction = "status" | "install" | "uninstall";

/** Where to install the skill. */
export type SkillScope = "personal" | "project";

/** Which agent target(s) to manage. */
export type SkillAgentSelection = "all" | "codex" | "claude-code" | "opencode";

/** A concrete agent a skill is installed for (no `all`). */
export type SkillAgent = "codex" | "claude-code" | "opencode";

/** Options shared by every skill action. */
export interface SkillOptions {
  agent: SkillAgentSelection;
  scope: SkillScope;
  /** Explicit skills directory; requires a single concrete `agent`. */
  skillsDir?: string;
  /** Overwrite or remove a skill that this tool did not manage. */
  force?: boolean;
}

/** A skill admin failure with an operator-facing message and optional hint. */
export class SkillError extends Error {
  readonly hint?: string;
  constructor(message: string, hint?: string) {
    super(message);
    this.name = "SkillError";
    this.hint = hint;
  }
}

/** Per-target outcome of `status` / `install`. */
export interface SkillTargetStatus {
  agent: SkillAgent;
  scope: SkillScope;
  skills_dir: string;
  skill_path: string;
  installed: boolean;
  managed: boolean;
  valid: boolean;
  current: boolean;
  validation_error: string | null;
}

/** Per-target outcome of `uninstall`. */
export interface SkillUninstallStatus {
  agent: SkillAgent;
  scope: SkillScope;
  skills_dir: string;
  skill_path: string;
  removed: boolean;
}

/**
 * The result of a skill action. Read fields off the discriminated union (narrow on
 * `code`), or pass it to `cliOutput` to serialize — every field is already JSON-shaped.
 */
export type SkillReport =
  | {
      code: "skill_status";
      skill: string;
      installed_all: boolean;
      valid_all: boolean;
      current_all: boolean;
      targets: SkillTargetStatus[];
    }
  | {
      code: "skill_install";
      skill: string;
      installed: boolean;
      targets: SkillTargetStatus[];
      hint: string;
    }
  | {
      code: "skill_uninstall";
      skill: string;
      removed_any: boolean;
      targets: SkillUninstallStatus[];
    };

interface SkillTarget {
  agent: SkillAgent;
  scope: SkillScope;
  skillsDir: string;
  skillDir: string;
  skillPath: string;
}

/**
 * Install, uninstall, or report status of `spec`'s skill across the selected agent
 * target(s). Returns the protocol value (caller renders with `cliOutput`) or throws a
 * {@link SkillError}. Does not touch stdout/stderr.
 */
export function runSkillAdmin(spec: SkillSpec, action: SkillAction, options: SkillOptions): SkillReport {
  switch (action) {
    case "status":
      return status(spec, options);
    case "install":
      return install(spec, options);
    case "uninstall":
      return uninstall(spec, options);
    default:
      throw new SkillError(`unknown skill action '${action as string}'`);
  }
}

function status(spec: SkillSpec, options: SkillOptions): SkillReport {
  const targets = resolveTargets(spec, options);
  const statuses = targets.map((target) => targetStatus(spec, target));
  return {
    code: "skill_status",
    skill: spec.name,
    installed_all: statuses.every((s) => s.installed),
    valid_all: statuses.every((s) => s.valid),
    current_all: statuses.every((s) => s.current),
    targets: statuses,
  };
}

function install(spec: SkillSpec, options: SkillOptions): SkillReport {
  validateSkillText(spec, spec.source);
  const targets = resolveTargets(spec, options);
  const content = managedSkillContents(spec);
  const installed: SkillTargetStatus[] = [];
  for (const target of targets) {
    fs.mkdirSync(target.skillDir, { recursive: true });
    if (fs.existsSync(target.skillPath) && !isManagedOrBundledSkill(spec, target.skillPath) && !options.force) {
      throw new SkillError(
        `refusing to overwrite unmanaged skill at ${target.skillPath}`,
        "pass --force to replace it, or choose another --skills-dir",
      );
    }
    fs.writeFileSync(target.skillPath, content);
    validateInstalledSkill(spec, target.skillPath);
    installed.push(targetStatus(spec, target));
  }
  return {
    code: "skill_install",
    skill: spec.name,
    installed: true,
    targets: installed,
    hint: "restart the agent so it reloads installed skills",
  };
}

function uninstall(spec: SkillSpec, options: SkillOptions): SkillReport {
  const targets = resolveTargets(spec, options);
  const removed: SkillUninstallStatus[] = [];
  for (const target of targets) {
    if (!fs.existsSync(target.skillPath)) {
      removed.push(targetUninstallStatus(target, false));
      continue;
    }
    if (!isManagedOrBundledSkill(spec, target.skillPath) && !options.force) {
      throw new SkillError(
        `refusing to remove unmanaged skill at ${target.skillPath}`,
        `only skills generated by ${spec.markerSlug} skill install can be removed without --force`,
      );
    }
    fs.rmSync(target.skillPath);
    // Prune the now-empty skill dir; ignore if not empty.
    try {
      fs.rmdirSync(target.skillDir);
    } catch {
      // directory not empty or already gone
    }
    removed.push(targetUninstallStatus(target, true));
  }
  return {
    code: "skill_uninstall",
    skill: spec.name,
    removed_any: removed.some((s) => s.removed),
    targets: removed,
  };
}

function resolveTargets(spec: SkillSpec, options: SkillOptions): SkillTarget[] {
  if (options.skillsDir !== undefined && options.agent === "all") {
    throw new SkillError(
      "--skills-dir requires a single --agent",
      "custom skills directories are ambiguous when --agent all is used",
    );
  }
  const { agent, scope } = options;
  if (agent === "all" && scope === "personal") {
    return [
      resolveTarget(spec, "codex", "personal", undefined),
      resolveTarget(spec, "claude-code", "personal", undefined),
      resolveTarget(spec, "opencode", "personal", undefined),
    ];
  }
  // Codex has no project scope, so --agent all --scope project skips it.
  if (agent === "all" && scope === "project") {
    return [
      resolveTarget(spec, "claude-code", "project", undefined),
      resolveTarget(spec, "opencode", "project", undefined),
    ];
  }
  if (agent === "codex" && scope === "project") {
    throw new SkillError(
      "Codex project skill scope is not supported",
      "use personal scope for Codex, or --agent claude-code/opencode --scope project",
    );
  }
  if (agent === "codex") {
    return [resolveTarget(spec, "codex", "personal", options.skillsDir)];
  }
  if (agent === "claude-code") {
    return [resolveTarget(spec, "claude-code", scope, options.skillsDir)];
  }
  if (agent === "opencode") {
    return [resolveTarget(spec, "opencode", scope, options.skillsDir)];
  }
  throw new SkillError(`invalid --agent '${agent as string}'`);
}

function resolveTarget(
  spec: SkillSpec,
  agent: SkillAgent,
  scope: SkillScope,
  skillsDir: string | undefined,
): SkillTarget {
  const base = skillsDir !== undefined ? expandTilde(skillsDir) : defaultSkillsDir(agent, scope);
  const skillDir = join(base, spec.name);
  return {
    agent,
    scope,
    skillsDir: base,
    skillDir,
    skillPath: join(skillDir, SKILL_FILE_NAME),
  };
}

function defaultSkillsDir(agent: SkillAgent, scope: SkillScope): string {
  if (agent === "codex") {
    if (scope === "project") {
      throw new SkillError("Codex project skill scope is not supported");
    }
    const codexHome = process.env["CODEX_HOME"];
    if (codexHome !== undefined) {
      return join(codexHome, "skills");
    }
    return join(homeDir(), ".codex", "skills");
  }
  if (agent === "claude-code") {
    if (scope === "project") {
      return join(process.cwd(), ".claude", "skills");
    }
    return join(homeDir(), ".claude", "skills");
  }
  // opencode
  if (scope === "project") {
    return join(process.cwd(), ".opencode", "skills");
  }
  const xdg = process.env["XDG_CONFIG_HOME"];
  if (xdg !== undefined) {
    return join(xdg, "opencode", "skills");
  }
  return join(homeDir(), ".config", "opencode", "skills");
}

function targetStatus(spec: SkillSpec, target: SkillTarget): SkillTargetStatus {
  const installed = isFile(target.skillPath);
  let valid = false;
  let current = false;
  let managed = false;
  let validationError: string | null = null;
  if (installed) {
    const text = fs.readFileSync(target.skillPath, "utf-8");
    managed = skillTextIsManagedOrBundled(spec, text);
    current = normalizeSkillText(spec, text) === normalizeSkillText(spec, spec.source);
    const error = validateSkillFrontmatter(text);
    if (error === null) {
      valid = true;
    } else {
      validationError = error;
    }
  }
  return {
    agent: target.agent,
    scope: target.scope,
    skills_dir: target.skillsDir,
    skill_path: target.skillPath,
    installed,
    managed,
    valid,
    current,
    validation_error: validationError,
  };
}

function targetUninstallStatus(target: SkillTarget, removed: boolean): SkillUninstallStatus {
  return {
    agent: target.agent,
    scope: target.scope,
    skills_dir: target.skillsDir,
    skill_path: target.skillPath,
    removed,
  };
}

function generatedBy(spec: SkillSpec): string {
  return `Generated by ${spec.markerSlug} skill install`;
}

function marker(spec: SkillSpec): string {
  return `${spec.markerSlug}-managed-skill: true`;
}

function managedSkillContents(spec: SkillSpec): string {
  const gen = generatedBy(spec);
  const mark = marker(spec);
  const lines = splitLines(spec.source);
  const out: string[] = [];
  let inserted = false;
  lines.forEach((line, i) => {
    out.push(line);
    if (i === 0) return;
    if (!inserted && line.trim() === "---") {
      out.push(`<!-- ${gen} -->`, `<!-- ${mark} -->`, "");
      inserted = true;
    }
  });
  if (!inserted) {
    out.push(`<!-- ${gen} -->`, `<!-- ${mark} -->`);
  }
  return out.map((line) => line + "\n").join("");
}

function validateInstalledSkill(spec: SkillSpec, path: string): void {
  validateSkillText(spec, fs.readFileSync(path, "utf-8"));
}

function validateSkillText(spec: SkillSpec, text: string): void {
  const error = validateSkillFrontmatter(text);
  if (error !== null) {
    throw new SkillError(
      `invalid ${spec.title} skill front matter: ${error}`,
      "quote scalar values that contain ': ', especially description",
    );
  }
}

function validateSkillFrontmatter(text: string): string | null {
  const lines = splitLines(text);
  if (lines.length === 0) {
    return "missing YAML front matter";
  }
  if (lines[0]!.trim() !== "---") {
    return "missing opening --- YAML front matter delimiter";
  }
  let foundEnd = false;
  let hasName = false;
  let hasDescription = false;
  for (let idx = 1; idx < lines.length; idx++) {
    const line = lines[idx]!;
    const lineNo = idx + 1;
    const trimmed = line.trim();
    if (trimmed === "---") {
      foundEnd = true;
      break;
    }
    if (trimmed === "" || trimmed.startsWith("#")) {
      continue;
    }
    if (line.startsWith(" ") || line.startsWith("\t")) {
      return `line ${lineNo}: nested YAML is not supported here`;
    }
    const colon = line.indexOf(":");
    if (colon === -1) {
      return `line ${lineNo}: expected key: value`;
    }
    const key = line.slice(0, colon).trim();
    if (key === "") {
      return `line ${lineNo}: empty key`;
    }
    const value = line.slice(colon + 1).replace(/^\s+/, "");
    if (key === "name") hasName = true;
    if (key === "description") hasDescription = true;
    if (value.startsWith('"') || value.startsWith("'")) {
      continue;
    }
    if (value.includes(": ")) {
      return `line ${lineNo}: unquoted scalar contains ': '; quote the value`;
    }
  }
  if (!foundEnd) {
    return "missing closing --- YAML front matter delimiter";
  }
  if (!hasName) {
    return "missing required name field";
  }
  if (!hasDescription) {
    return "missing required description field";
  }
  return null;
}

function isManagedOrBundledSkill(spec: SkillSpec, path: string): boolean {
  if (!fs.existsSync(path)) {
    return false;
  }
  return skillTextIsManagedOrBundled(spec, fs.readFileSync(path, "utf-8"));
}

function skillTextIsManagedOrBundled(spec: SkillSpec, text: string): boolean {
  const mark = marker(spec);
  const gen = generatedBy(spec);
  if (text.includes(mark) && text.includes(gen)) {
    return true;
  }
  return normalizeSkillText(spec, text) === normalizeSkillText(spec, spec.source);
}

/**
 * Drop the managed-marker lines, then collapse runs of blank lines to one so that the
 * blank line `managedSkillContents` inserts after the marker block does not make a
 * managed install compare unequal to the bundled source.
 */
function normalizeSkillText(spec: SkillSpec, text: string): string {
  const mark = marker(spec);
  const gen = generatedBy(spec);
  const out: string[] = [];
  for (const line of splitLines(text)) {
    const trimmed = line.trim();
    if (trimmed.includes(mark) || trimmed.includes(gen)) {
      continue;
    }
    if (trimmed === "" && out.length > 0 && out[out.length - 1]!.trim() === "") {
      continue;
    }
    out.push(line);
  }
  return out.join("\n").trim();
}

function homeDir(): string {
  const home = process.env["HOME"] ?? process.env["USERPROFILE"];
  if (home !== undefined) {
    return home;
  }
  throw new SkillError("cannot determine home directory", "pass --skills-dir explicitly");
}

function expandTilde(input: string): string {
  if (input === "~") {
    return homeDir();
  }
  if (input.startsWith("~/")) {
    return join(homeDir(), input.slice(2));
  }
  return input;
}

/**
 * Mirror Rust's `str::lines`: split on `\n` (normalizing `\r\n`), dropping a single
 * trailing empty element from a final newline.
 */
function isFile(p: string): boolean {
  const st = fs.statSync(p, { throwIfNoEntry: false });
  return st !== undefined && st.isFile();
}

function splitLines(s: string): string[] {
  const lines = s.replace(/\r\n/g, "\n").split("\n");
  if (lines.length > 0 && lines[lines.length - 1] === "") {
    lines.pop();
  }
  return lines;
}
