/**
 * Tests for the skill admin module, mirroring the Rust port's coverage.
 */

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import * as fs from "node:fs";
import * as os from "node:os";
import { join } from "node:path";
import { runSkillAdmin, SkillError, type SkillOptions, type SkillSpec } from "./index.js";

const SKILL_SOURCE = "---\nname: agent-first-test\ndescription: test skill\n---\n\n# Body\n\nrules.\n";
const SKILL_FILE_NAME = "SKILL.md";
const MARKER = "aftest-managed-skill: true";
const GENERATED_BY = "Generated by aftest skill install";

function spec(): SkillSpec {
  return {
    name: "agent-first-test",
    source: SKILL_SOURCE,
    title: "Agent-First Test",
    markerSlug: "aftest",
  };
}

function tempDir(): string {
  return fs.mkdtempSync(join(os.tmpdir(), "afdata-skill-"));
}

function options(agent: SkillOptions["agent"], skillsDir: string, force = false): SkillOptions {
  return { agent, scope: "personal", skillsDir, force };
}

describe("skill admin", () => {
  it("install → status → uninstall per agent", () => {
    for (const [agent, expect] of [
      ["codex", "codex"],
      ["claude-code", "claude-code"],
      ["opencode", "opencode"],
    ] as const) {
      const dir = tempDir();
      const opts = options(agent, dir);
      const skillPath = join(dir, "agent-first-test", SKILL_FILE_NAME);

      runSkillAdmin(spec(), "install", opts);
      assert.ok(fs.statSync(skillPath).isFile());
      assert.ok(fs.readFileSync(skillPath, "utf-8").includes(MARKER));

      const report = runSkillAdmin(spec(), "status", opts);
      assert.equal(report.code, "skill_status");
      if (report.code !== "skill_status") throw new Error("unreachable");
      assert.equal(report.installed_all, true);
      assert.equal(report.valid_all, true);
      assert.equal(report.current_all, true);
      assert.equal(report.targets[0]!.agent, expect);
      assert.equal(report.targets[0]!.current, true);

      runSkillAdmin(spec(), "uninstall", opts);
      assert.ok(!fs.existsSync(skillPath));
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it("returns the typed install report", () => {
    const dir = tempDir();
    const report = runSkillAdmin(spec(), "install", options("opencode", dir));
    assert.equal(report.code, "skill_install");
    if (report.code !== "skill_install") throw new Error("unreachable");
    assert.equal(report.installed, true);
    assert.equal(report.targets[0]!.agent, "opencode");
    assert.equal(report.targets[0]!.current, true);
    fs.rmSync(dir, { recursive: true, force: true });
  });

  it("reports a stale install as not current, refreshes on reinstall", () => {
    const dir = tempDir();
    const opts = options("opencode", dir);
    const skillDir = join(dir, "agent-first-test");
    fs.mkdirSync(skillDir, { recursive: true });
    const stale = `---\nname: agent-first-test\ndescription: test skill\n---\n<!-- ${GENERATED_BY} -->\n<!-- ${MARKER} -->\n\n# Body\n\nOLD rules.\n`;
    fs.writeFileSync(join(skillDir, SKILL_FILE_NAME), stale);

    const report = runSkillAdmin(spec(), "status", opts);
    if (report.code !== "skill_status") throw new Error("unreachable");
    assert.equal(report.current_all, false);
    const target = report.targets[0]!;
    assert.equal(target.installed, true);
    assert.equal(target.valid, true);
    assert.equal(target.managed, true);
    assert.equal(target.current, false);

    runSkillAdmin(spec(), "install", opts);
    const after = runSkillAdmin(spec(), "status", opts);
    if (after.code !== "skill_status") throw new Error("unreachable");
    assert.equal(after.targets[0]!.current, true);
    fs.rmSync(dir, { recursive: true, force: true });
  });

  it("install and uninstall refuse unmanaged skills", () => {
    const dir = tempDir();
    const skillDir = join(dir, "agent-first-test");
    fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(join(skillDir, SKILL_FILE_NAME), "---\nname: custom\ndescription: custom\n---\n");
    const opts = options("codex", dir);

    assert.throws(() => runSkillAdmin(spec(), "install", opts), SkillError);
    assert.throws(() => runSkillAdmin(spec(), "uninstall", opts), SkillError);
    assert.ok(fs.existsSync(join(skillDir, SKILL_FILE_NAME)));
    fs.rmSync(dir, { recursive: true, force: true });
  });

  it("rejects bundled source with invalid front matter on install", () => {
    const dir = tempDir();
    const bad: SkillSpec = { ...spec(), source: "---\nname: x\ndescription: broken: yaml\n---\n" };
    assert.throws(() => runSkillAdmin(bad, "install", options("opencode", dir)), SkillError);
    fs.rmSync(dir, { recursive: true, force: true });
  });

  it("--agent all --scope personal resolves three targets", () => {
    const report = runSkillAdmin(spec(), "status", { agent: "all", scope: "personal" });
    if (report.code !== "skill_status") throw new Error("unreachable");
    assert.deepEqual(report.targets.map((t) => t.agent), ["codex", "claude-code", "opencode"]);
  });

  it("--agent all --scope project skips codex", () => {
    const report = runSkillAdmin(spec(), "status", { agent: "all", scope: "project" });
    if (report.code !== "skill_status") throw new Error("unreachable");
    assert.deepEqual(report.targets.map((t) => t.agent), ["claude-code", "opencode"]);
  });

  it("rejects codex project scope", () => {
    assert.throws(() => runSkillAdmin(spec(), "status", { agent: "codex", scope: "project" }), SkillError);
  });

  it("rejects --skills-dir with --agent all", () => {
    assert.throws(
      () => runSkillAdmin(spec(), "status", { agent: "all", scope: "personal", skillsDir: "/tmp/x" }),
      SkillError,
    );
  });
});
