/**
 * Tests for the skill admin module, mirroring the Rust port's coverage.
 */

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import * as fs from "node:fs";
import * as os from "node:os";
import { join } from "node:path";
import { runSkillAdmin, SkillError, type SkillOptions, type SkillSpec } from "./skill.js";

const SKILL_SOURCE = "---\nname: agent-first-test\ndescription: test skill\n---\n\n# Body\n\nrules.\n";
const SKILL_FILE_NAME = "SKILL.md";
const MARKER = "aftest-managed-skill: true";
const GENERATED_BY = "Generated by aftest skill install";
const LEGACY_MARKER_BLOCK = `<!-- ${GENERATED_BY} -->\n<!-- ${MARKER} -->`;

function spec(): SkillSpec {
  return {
    name: "agent-first-test",
    source: SKILL_SOURCE,
    title: "Agent-First Test",
    markerSlug: "aftest",
  };
}

function tempDir(): string {
  return fs.mkdtempSync(join(os.tmpdir(), "afdata-skill-"));
}

function options(agent: SkillOptions["agent"], skillsDir: string, force = false): SkillOptions {
  return { agent, scope: "personal", skillsDir, force };
}

function legacyManagedSkill(body: string): string {
  return `---\nname: agent-first-test\ndescription: test skill\n---\n${LEGACY_MARKER_BLOCK}\n\n${body}`;
}

describe("skill admin", () => {
  it("install → status → uninstall per agent", () => {
    for (const [agent, expect] of [
      ["codex", "codex"],
      ["claude-code", "claude-code"],
      ["opencode", "opencode"],
      ["hermes", "hermes"],
    ] as const) {
      const dir = tempDir();
      const opts = options(agent, dir);
      const skillPath = join(dir, "agent-first-test", SKILL_FILE_NAME);

      runSkillAdmin(spec(), "install", opts);
      assert.ok(fs.statSync(skillPath).isFile());
      const installedText = fs.readFileSync(skillPath, "utf-8");
      assert.ok(installedText.includes("aftest-managed-skill-name: agent-first-test"));
      assert.ok(installedText.includes("aftest-managed-skill-source-hash-fnv1a64:"));
      assert.ok(installedText.includes(MARKER));

      const report = runSkillAdmin(spec(), "status", opts);
      assert.equal(report.code, "skill_status");
      if (report.code !== "skill_status") throw new Error("unreachable");
      assert.equal(report.installed_all, true);
      assert.equal(report.valid_all, true);
      assert.equal(report.current_all, true);
      assert.equal(report.targets[0]!.agent, expect);
      assert.equal(report.targets[0]!.current, true);

      runSkillAdmin(spec(), "uninstall", opts);
      assert.ok(!fs.existsSync(skillPath));
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it("returns the typed install report", () => {
    const dir = tempDir();
    const report = runSkillAdmin(spec(), "install", options("opencode", dir));
    assert.equal(report.code, "skill_install");
    if (report.code !== "skill_install") throw new Error("unreachable");
    assert.equal(report.installed, true);
    assert.equal(report.targets[0]!.agent, "opencode");
    assert.equal(report.targets[0]!.current, true);
    fs.rmSync(dir, { recursive: true, force: true });
  });

  it("reports a stale install as not current, refreshes on reinstall", () => {
    const dir = tempDir();
    const opts = options("opencode", dir);
    const skillDir = join(dir, "agent-first-test");
    fs.mkdirSync(skillDir, { recursive: true });
    const stale = legacyManagedSkill("# Body\n\nOLD rules.\n");
    fs.writeFileSync(join(skillDir, SKILL_FILE_NAME), stale);

    const report = runSkillAdmin(spec(), "status", opts);
    if (report.code !== "skill_status") throw new Error("unreachable");
    assert.equal(report.current_all, false);
    const target = report.targets[0]!;
    assert.equal(target.installed, true);
    assert.equal(target.valid, true);
    assert.equal(target.managed, true);
    assert.equal(target.current, false);

    runSkillAdmin(spec(), "install", opts);
    const refreshed = fs.readFileSync(join(skillDir, SKILL_FILE_NAME), "utf-8");
    assert.ok(refreshed.includes("aftest-managed-skill-name: agent-first-test"));
    assert.ok(!refreshed.includes(`<!-- ${MARKER} -->`));
    const after = runSkillAdmin(spec(), "status", opts);
    if (after.code !== "skill_status") throw new Error("unreachable");
    assert.equal(after.targets[0]!.current, true);
    fs.rmSync(dir, { recursive: true, force: true });
  });

  it("does not treat random marker words as managed", () => {
    const dir = tempDir();
    const opts = options("opencode", dir);
    const skillDir = join(dir, "agent-first-test");
    fs.mkdirSync(skillDir, { recursive: true });
    const random = `---\nname: agent-first-test\ndescription: test skill\n---\n\nThis mentions ${GENERATED_BY} and ${MARKER} but is not a generated block.\n`;
    fs.writeFileSync(join(skillDir, SKILL_FILE_NAME), random);

    const report = runSkillAdmin(spec(), "status", opts);
    if (report.code !== "skill_status") throw new Error("unreachable");
    assert.equal(report.targets[0]!.managed, false);
    assert.throws(() => runSkillAdmin(spec(), "install", opts), SkillError);
    fs.rmSync(dir, { recursive: true, force: true });
  });

  it("install and uninstall refuse unmanaged skills", () => {
    const dir = tempDir();
    const skillDir = join(dir, "agent-first-test");
    fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(join(skillDir, SKILL_FILE_NAME), "---\nname: custom\ndescription: custom\n---\n");
    const opts = options("codex", dir);

    assert.throws(() => runSkillAdmin(spec(), "install", opts), SkillError);
    assert.throws(() => runSkillAdmin(spec(), "uninstall", opts), SkillError);
    assert.ok(fs.existsSync(join(skillDir, SKILL_FILE_NAME)));
    fs.rmSync(dir, { recursive: true, force: true });
  });

  it("rejects bundled source with invalid front matter on install", () => {
    const dir = tempDir();
    const bad: SkillSpec = { ...spec(), source: "---\nname: x\ndescription: broken: yaml\n---\n" };
    assert.throws(() => runSkillAdmin(bad, "install", options("opencode", dir)), SkillError);
    fs.rmSync(dir, { recursive: true, force: true });
  });

  it("rejects unsafe skill names and marker slugs before path resolution", () => {
    for (const name of ["", "../x", "x/y", ".hidden", "bad_name", "Bad"]) {
      const bad: SkillSpec = { ...spec(), name };
      assert.throws(() => runSkillAdmin(bad, "status", options("codex", tempDir())), SkillError);
    }
    const badMarker: SkillSpec = { ...spec(), markerSlug: "../aftest" };
    assert.throws(() => runSkillAdmin(badMarker, "status", options("codex", tempDir())), SkillError);
  });

  it("requires bundled front matter name to match the spec name", () => {
    const dir = tempDir();
    const bad: SkillSpec = { ...spec(), source: "---\nname: other-skill\ndescription: test skill\n---\n" };
    assert.throws(() => runSkillAdmin(bad, "install", options("opencode", dir)), SkillError);
    fs.rmSync(dir, { recursive: true, force: true });
  });

  it("rejects symlink targets by default and force install does not follow them", () => {
    const dir = tempDir();
    const opts = options("codex", dir);
    const forceOpts = options("codex", dir, true);
    const skillDir = join(dir, "agent-first-test");
    const skillPath = join(skillDir, SKILL_FILE_NAME);
    const external = join(dir, "external.md");
    fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(external, "external");
    try {
      fs.symlinkSync(external, skillPath);
    } catch {
      fs.rmSync(dir, { recursive: true, force: true });
      return;
    }

    assert.throws(() => runSkillAdmin(spec(), "install", opts), SkillError);
    assert.equal(fs.readFileSync(external, "utf-8"), "external");
    assert.throws(() => runSkillAdmin(spec(), "uninstall", opts), SkillError);
    assert.equal(fs.lstatSync(skillPath).isSymbolicLink(), true);

    runSkillAdmin(spec(), "install", forceOpts);
    assert.equal(fs.readFileSync(external, "utf-8"), "external");
    assert.equal(fs.lstatSync(skillPath).isSymbolicLink(), false);
    assert.equal(fs.statSync(skillPath).isFile(), true);
    fs.rmSync(dir, { recursive: true, force: true });
  });

  it("force uninstall removes symlink without following it", () => {
    const dir = tempDir();
    const forceOpts = options("codex", dir, true);
    const skillDir = join(dir, "agent-first-test");
    const skillPath = join(skillDir, SKILL_FILE_NAME);
    const external = join(dir, "external.md");
    fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(external, "external");
    try {
      fs.symlinkSync(external, skillPath);
    } catch {
      fs.rmSync(dir, { recursive: true, force: true });
      return;
    }

    runSkillAdmin(spec(), "uninstall", forceOpts);
    assert.equal(fs.existsSync(skillPath), false);
    assert.equal(fs.readFileSync(external, "utf-8"), "external");
    fs.rmSync(dir, { recursive: true, force: true });
  });

  it("--agent all --scope personal resolves four targets", () => {
    const report = runSkillAdmin(spec(), "status", { agent: "all", scope: "personal" });
    if (report.code !== "skill_status") throw new Error("unreachable");
    assert.deepEqual(report.targets.map((t) => t.agent), ["codex", "claude-code", "opencode", "hermes"]);
  });

  it("--agent all --scope workspace resolves four targets", () => {
    const report = runSkillAdmin(spec(), "status", { agent: "all", scope: "workspace" });
    if (report.code !== "skill_status") throw new Error("unreachable");
    assert.deepEqual(report.targets.map((t) => t.agent), ["codex", "claude-code", "opencode", "hermes"]);
    assert.deepEqual(report.targets.map((t) => t.scope), ["workspace", "workspace", "workspace", "workspace"]);
  });

  it("uses the codex workspace skills dir", () => {
    const report = runSkillAdmin(spec(), "status", { agent: "codex", scope: "workspace" });
    if (report.code !== "skill_status") throw new Error("unreachable");
    assert.deepEqual(report.targets.map((t) => t.agent), ["codex"]);
    assert.deepEqual(report.targets.map((t) => t.scope), ["workspace"]);
    assert.match(report.targets[0].skills_dir, /\.codex\/skills$/);
  });

  it("uses the hermes workspace skills dir", () => {
    const report = runSkillAdmin(spec(), "status", { agent: "hermes", scope: "workspace" });
    if (report.code !== "skill_status") throw new Error("unreachable");
    assert.deepEqual(report.targets.map((t) => t.agent), ["hermes"]);
    assert.deepEqual(report.targets.map((t) => t.scope), ["workspace"]);
    assert.match(report.targets[0].skills_dir, /\.hermes\/skills$/);
  });

  it("rejects --skills-dir with --agent all", () => {
    assert.throws(
      () => runSkillAdmin(spec(), "status", { agent: "all", scope: "personal", skillsDir: "/tmp/x" }),
      SkillError,
    );
  });
});
