"""Agent-First Data (AFDATA) — suffix-driven output formatting and protocol templates."""

from agent_first_data.format import (
    build_json_ok,
    build_json_error,
    build_json,
    RedactionPolicy,
    RedactionOptions,
    OutputStyle,
    OutputOptions,
    output_json,
    output_json_with,
    output_json_with_options,
    output_yaml,
    output_yaml_with_options,
    output_plain,
    output_plain_with_options,
    internal_redact_secrets,
    internal_redact_secrets_with_options,
    redacted_value,
    redacted_value_with,
    redacted_value_with_options,
    redact_url_secrets,
    redact_url_secrets_with_options,
    parse_size,
)

from agent_first_data.afdata_logging import (
    AfdataHandler,
    init_json as init_logging_json,
    init_plain as init_logging_plain,
    init_yaml as init_logging_yaml,
    get_logger,
    span,
)

from agent_first_data.cli import (
    OutputFormat,
    cli_parse_output,
    cli_parse_log_filters,
    cli_output,
    cli_output_with_options,
    build_cli_error,
)

from agent_first_data.skill import (
    SkillSpec,
    SkillAction,
    SkillScope,
    SkillAgentSelection,
    SkillAgent,
    SkillOptions,
    SkillError,
    SkillTargetStatus,
    SkillUninstallStatus,
    SkillStatusReport,
    SkillInstallReport,
    SkillUninstallReport,
    run_skill_admin,
)

__all__ = [
    "build_json_ok",
    "build_json_error",
    "build_json",
    "RedactionPolicy",
    "RedactionOptions",
    "OutputStyle",
    "OutputOptions",
    "output_json",
    "output_json_with",
    "output_json_with_options",
    "output_yaml",
    "output_yaml_with_options",
    "output_plain",
    "output_plain_with_options",
    "internal_redact_secrets",
    "internal_redact_secrets_with_options",
    "redacted_value",
    "redacted_value_with",
    "redacted_value_with_options",
    "redact_url_secrets",
    "redact_url_secrets_with_options",
    "parse_size",
    "AfdataHandler",
    "init_logging_json",
    "init_logging_plain",
    "init_logging_yaml",
    "get_logger",
    "span",
    "OutputFormat",
    "cli_parse_output",
    "cli_parse_log_filters",
    "cli_output",
    "cli_output_with_options",
    "build_cli_error",
    "SkillSpec",
    "SkillAction",
    "SkillScope",
    "SkillAgentSelection",
    "SkillAgent",
    "SkillOptions",
    "SkillError",
    "SkillTargetStatus",
    "SkillUninstallStatus",
    "SkillStatusReport",
    "SkillInstallReport",
    "SkillUninstallReport",
    "run_skill_admin",
]
